# Generated by Django 4.1.1 on 2022-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=" hey", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Publish")], default=0
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
